name: pre-commit
description: ""

inputs:
  pre-commit-config:
    description: ""
    required: true
  token:
    description: ""
    required: false

runs:
  using: composite
  steps:
    # shfmt requires Go 1.16+
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Run pre-commit
      uses: pre-commit/action@v2.0.3
      with:
        extra_args: --all-files --config ${{ inputs.pre-commit-config }}
        token: ${{ inputs.token }}
