name: pre-commit
description: ""

inputs:
  pre-commit-config:
    description: ""
    required: true
  base-branch:
    description: ""
    required: false
    default: ${{ github.base_ref }}
  token:
    description: ""
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Set git config
      uses: autowarefoundation/autoware-github-actions/set-git-config@v1
      with:
        token: ${{ inputs.token }}

    - name: Get modified files
      id: get-modified-files
      run: |
        git log -1 --oneline HEAD
        git log -1 --oneline "${{ inputs.base-branch }}"
        modified_files=$(git diff --name-only "${{ inputs.base-branch }}"...HEAD)
        echo "modified-files=${modified_files}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Show result
      run: |
        echo "modified-files: ${{ steps.get-modified-files.outputs.modified-files }}"
      shell: bash

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --config ${{ inputs.pre-commit-config }} --files ${{ steps.get-modified-files.outputs.modified-files }}

    - name: Push pre-commit fixes
      if: always() # Push changes even when pre-commit fails
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "style(pre-commit): autofix"
