name: pre-commit
description: ""

inputs:
  pre-commit-config:
    description: ""
    required: true
  token:
    description: ""
    required: false

runs:
  using: composite
  steps:
    # shfmt requires Go 1.16+
    - name: Set up go
      uses: actions/setup-go@v3
      with:
        go-version: ^1.16

    - name: Install pre-commit
      run: |
        python -m pip install pre-commit
      shell: bash

    - name: Run pre-commit
      run: |
        pre-commit run -a
      shell: bash

    - name: Push pre-commit fixes
      # Prevent a workflow from stopping when pre-commit fails
      if: always()
      run: |
        if ! git diff --quiet; then
          git add -u
          git commit -m "pre-commit fixes"
          git push
        fi
      shell: bash
