name: remove-exec-depend
description: ""

runs:
  using: composite
  steps:
    - name: Remove exec_depend
      run: |
        find . -name package.xml | xargs -I {} sed -i -rz "s|<exec_depend>\s*[a-zA-Z0-9_-]+\s*</exec_depend>\n||g" {}
      shell: bash
