name: spell-check
description: ""

inputs:
  cspell-json-url:
    description: ""
    required: true
  local-cspell-json:
    description: ""
    required: false
    default: .cspell.json
  token:
    description: ""
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Retrieve remote dictionary
      run: |
        curl -fsSL -o remote.cspell.json ${{ inputs.cspell-json-url }} \
          -H "Authorization: token ${{ inputs.token }}"
      shell: bash

    - name: Prepare local dictionary
      run: |
        echo "{}" > local.cspell.json
        cp ${{ inputs.local-cspell-json }} local.cspell.json || true
      shell: bash

    - name: Create combined dictionary
      run: |
        echo '{ "import": ["./remote.cspell.json", "./local.cspell.json"] }' > .cspell.json
      shell: bash

    - name: Run spell check
      uses: streetsidesoftware/cspell-action@v2
      with:
        config: .cspell.json
