name: colcon-build-and-test
description: ""

inputs:
  rosdistro:
    description: ""
    required: true
  target-packages:
    description: ""
    required: true
  build-depends-repos:
    description: ""
    required: false
  token:
    description: ""
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Show deprecated warning
      run: echo "::warning title=DEPRECATED::colcon-build-and-test action will no longer be available in future releases. Please consider using colcon-build and colcon-test workflows instead."
      shell: bash

    - name: Show target packages
      run: |
        echo "target packages: ${{ inputs.target-packages }}"
      shell: bash

    - name: Install pip for rosdep
      run: |
        sudo apt-get -yqq update
        sudo apt-get -yqq install python3-pip
      shell: bash

    - name: Set git config
      if: ${{ inputs.build-depends-repos != ''}}
      uses: autowarefoundation/autoware-github-actions/set-git-config@tier4/proposal
      with:
        token: ${{ inputs.token }}

    - name: Clone dependency packages
      if: ${{ inputs.build-depends-repos != ''}}
      run: |
        mkdir dependency_ws
        vcs import dependency_ws < ${{ inputs.build-depends-repos }}
      shell: bash

    - name: Run rosdep install
      run: |
        package_paths=$(colcon list -p --packages-above-and-dependencies ${{ inputs.target-packages }})
        sudo apt-get -yqq update
        rosdep update
        DEBIAN_FRONTEND=noninteractive rosdep install -yqq --from-paths ${package_paths} --ignore-src --rosdistro ${{ inputs.rosdistro }}
      shell: bash

    - name: Set up colcon-mixin
      run: |
        colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml || true
        colcon mixin update default
      shell: bash

    - name: Build
      run: |
        . /opt/ros/${{ inputs.rosdistro }}/setup.sh
        colcon build --event-handlers console_cohesion+ \
          --packages-above-and-dependencies ${{ inputs.target-packages }} \
          --cmake-args -DCMAKE_BUILD_TYPE=Release \
          --mixin coverage-gcc coverage-pytest compile-commands
      shell: bash

    - name: Install packages for coverage commands
      run: |
        sudo apt-get -yqq update
        sudo apt-get -yqq install lcov
        pip3 install colcon-lcov-result colcon-coveragepy-result
      shell: bash

    - name: Test
      run: |
        . /opt/ros/${{ inputs.rosdistro }}/setup.sh
        colcon lcov-result --initial --verbose --packages-above ${{ inputs.target-packages }}
        colcon test --event-handlers console_cohesion+ \
          --mixin coverage-pytest \
          --packages-above ${{ inputs.target-packages }} \
          --return-code-on-test-failure
        colcon lcov-result --verbose --packages-above ${{ inputs.target-packages }} || true
        colcon coveragepy-result --verbose --packages-above ${{ inputs.target-packages }} || true
      shell: bash

    - name: Cache build artifacts
      uses: actions/cache@v2
      with:
        path: |
          ./build
          ./install
        key: build-${{ github.sha }}
