name: generate-changelog
description: ""

inputs:
  git-cliff-args:
    description: ""
    required: false
    default: --current
  git-cliff-config:
    description: ""
    required: false
    default: ${GITHUB_ACTION_PATH}/../cliff.toml
  trim-version-and-date:
    description: ""
    required: false
    default: "true"
outputs:
  changelog:
    description: ""
    value: ${{ steps.generate-changelog.outputs.changelog }}

runs:
  using: composite
  steps:
    - name: Set config path
      id: set-git-cliff-config-path
      run: |
        echo "::set-output name=path::$(readlink -f ${{ inputs.git-cliff-config }})"
      shell: bash

    - name: Install git-cliff
      run: |
        curl -fsSL -o git-cliff.tar.gz https://github.com/orhun/git-cliff/releases/download/v${VERSION}/git-cliff-${VERSION}-x86_64-unknown-linux-gnu.tar.gz
        tar -xf git-cliff.tar.gz
        sudo cp git-cliff-${VERSION}/git-cliff /usr/local/bin/git-cliff
      env:
        VERSION: 0.5.0
      shell: bash

    - name: Generate changelog
      id: generate-changelog
      shell: bash
      run: |
        # Generate changelog
        git cliff --output CHANGELOG.md \
          --config ${{ steps.set-git-cliff-config-path.outputs.path }} \
          -vv --strip header ${{ inputs.git-cliff-args }}

        r=$(cat CHANGELOG.md)

        # Trim version and date
        if [ "${{ inputs.trim-version-and-date }}" = "true" ]; then
          r="$(printf "$r" | tail -n +3)"
        fi

        # Workaround for https://github.community/t/set-output-truncates-multiline-strings/16852
        r="${r//'%'/'%25'}"
        r="${r//$'\n'/'%0A'}"
        r="${r//$'\r'/'%0D'}"

        echo "::set-output name=changelog::$r"

    - name: Show result
      run: |
        echo "$CHANGELOG"
      env:
        CHANGELOG: ${{ steps.generate-changelog.outputs.changelog }}
      shell: bash
