name: json-schema-check
description: ""

runs:
  using: composite
  steps:
    - name: Install JSON Schema packages
      run: |
        pip3 install -U check-jsonschema
      shell: bash

    - name: Check configuration files
      run: |
        find -wholename '*/schema/*.schema.json' -execdir bash -c 'for f in $@; do check-jsonschema --schemafile $f ../config/`basename $f .schema.json`.param.yaml; done' bash '{}' +
      shell: bash
