name: file-check
description: ""

inputs:
  files:
    description: ""
    required: true
  condition:
    description: ""
    required: true
outputs:
  exists:
    description: ""
    value: ${{ steps.file-check.outputs.exists }}

runs:
  using: composite
  steps:
    - name: File check
      id: file-check
      run: |
        set -e

        # Split files into an array
        input_files="${{ inputs.files }}"
        file_array=(${input_files})

        # Iterate files
        exist_files=()
        for FILE in "${file_array[@]}"; do
          if [[ -f $FILE ]]; then
            echo "File exists: $FILE"
            exist_files+=("$FILE")
          else
            echo "File $FILE does not exist"
          fi
        done

        if [[ ${{ inputs.condition }} = "or" ]]; then
          if [[ ${#exist_files[@]} -gt 0 ]]; then
            echo ::set-output name=exists::"true"
          else
            echo ::set-output name=exists::"false"
          fi
        elif [[ ${{ inputs.condition }} = "and" ]]; then
          if [[ ${#exist_files[@]} -eq ${#file_array[@]} ]]; then
            echo ::set-output name=exists::"true"
          else
            echo ::set-output name=exists::"false"
          fi
        else
          echo ::set-output name=exists::"false"
        fi
      shell: bash
