name: check-file-existence
description: ""

inputs:
  files:
    description: ""
    required: true
  condition:
    description: ""
    required: true
outputs:
  exists:
    description: ""
    value: ${{ steps.check-file-existence.outputs.exists }}

runs:
  using: composite
  steps:
    - name: File check
      id: check-file-existence
      run: |
        set -e

        # Split files into an array
        input_files="${{ inputs.files }}"
        file_array=(${input_files})

        # Iterate files
        exist_files=()
        for f in "${file_array[@]}"; do
          if [[ -f $f ]]; then
            echo "File exists: $f"
            exist_files+=("$f")
          else
            echo "File $f does not exist"
          fi
        done

        if [[ "${{ inputs.condition }}" = "or" ]]; then
          if [[ ${#exist_files[@]} -gt 0 ]]; then
            echo ::set-output name=exists::"true"
          else
            echo ::set-output name=exists::"false"
          fi
        elif [[ ${{ inputs.condition }} = "and" ]]; then
          if [[ ${#exist_files[@]} -eq ${#file_array[@]} ]]; then
            echo ::set-output name=exists::"true"
          else
            echo ::set-output name=exists::"false"
          fi
        else
          echo ::set-output name=exists::"false"
        fi
      shell: bash
