name: register-autonomoustuff-repository
description: Register AutonomouStuff repositry into rosdep

inputs:
  rosdistro:
    description: ROS distro
    required: true

runs:
  using: composite
  steps:
    - name: Install apt-transport-https
      run: |
        apt-get -y update
        apt-get -y install apt-transport-https

    - name: Add Autonomoustuff repository
      run: |
        sh -c 'echo "yaml https://s3.amazonaws.com/autonomoustuff-repo/autonomoustuff-public-${{ inputs.rosdistro }}.yaml" > /etc/ros/rosdep/sources.list.d/40-autonomoustuff-public-${{ inputs.rosdistro }}.list'
        sh -c 'echo "deb [trusted=yes] https://s3.amazonaws.com/autonomoustuff-repo/ focal main" > /etc/apt/sources.list.d/autonomoustuff-public.list'
