name: register-autonomoustuff-repository
description: register-autonomoustuff-repository

inputs:
  rosdistro:
    description: ROS distro
    required: true

runs:
  using: composite
  steps:
    # https://github.com/astuff/pacmod3_msgs#installation
    - name: Register AutonomouStuff repository
      run: |
        sudo apt-get -y update
        sudo apt-get -y install apt-transport-https
        sudo sh -c 'echo "deb [trusted=yes] https://s3.amazonaws.com/autonomoustuff-repo/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/autonomoustuff-public.list'
        sudo apt-get -y update
      shell: bash
