name: get-modified-packages
description: ""

outputs:
  modified-packages:
    description: ""
    value: ${{ steps.get-modified-packages.outputs.modified-packages }}

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get modified packages
      id: get-modified-packages
      run: |
        ${GITHUB_ACTION_PATH}/get-modified-packages.sh origin/${{ github.base_ref }}
      shell: bash

    - name: Show result
      run: |
        echo "modified-packages: ${{ steps.get-modified-packages.outputs.modified-packages }}"
      shell: bash
