name: check-app-secrets

on:
  workflow_call:
    outputs:
      have_secrets:
        value: ${{ jobs.check-app-secrets.outputs.have_secrets }}

jobs:
  check-app-secrets:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.check-app-secrets.outputs.run }}
    steps:
      - name: Check secrets for GitHub App
        id: check-app-secrets
        run: |
          if [ "${{ secrets.APP_ID }}" = "" ] || [ "${{ secrets.PRIVATE_KEY }}" = "" ]; then
            echo "::info Please set secrets 'APP_ID' and 'PRIVATE_KEY' to run this workflow."
          else
            echo ::set-output name=have_secrets::true
          fi
        shell: bash

      - name: Show result
        run: |
          echo "have_secrets: ${{ steps.check-app-secrets.outputs.have_secrets }}"
        shell: bash
