name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run pre-commit
        uses: ./pre-commit
        with:
          pre-commit-config: .pre-commit-config.yaml
